export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS registration_invites (
    id TEXT PRIMARY KEY,
    code_hash TEXT NOT NULL UNIQUE,
    created_by TEXT,
    invite_role TEXT NOT NULL DEFAULT 'user' CHECK (invite_role IN ('admin', 'user')),
    allowed_email TEXT,
    max_uses INTEGER NOT NULL CHECK (max_uses > 0),
    used_count INTEGER NOT NULL DEFAULT 0 CHECK (used_count >= 0),
    expires_at TEXT,
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'disabled')),
    note TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS users (
    id TEXT PRIMARY KEY,
    email TEXT NOT NULL COLLATE NOCASE UNIQUE,
    password_hash TEXT,
    nickname TEXT NOT NULL,
    avatar_url TEXT,
    default_currency TEXT NOT NULL DEFAULT 'CNY',
    locale TEXT NOT NULL DEFAULT 'zh-CN',
    timezone TEXT NOT NULL DEFAULT 'Asia/Shanghai',
    system_role TEXT NOT NULL DEFAULT 'user' CHECK (system_role IN ('admin', 'user')),
    registration_invite_id TEXT,
    email_verified_at TEXT,
    last_login_at TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    FOREIGN KEY (registration_invite_id) REFERENCES registration_invites(id)
  )`,
  `CREATE TABLE IF NOT EXISTS oauth_accounts (
    id TEXT PRIMARY KEY,
    user_id TEXT NOT NULL,
    provider TEXT NOT NULL CHECK (provider IN ('google', 'github')),
    provider_user_id TEXT NOT NULL,
    provider_email TEXT,
    created_at TEXT NOT NULL,
    UNIQUE (provider, provider_user_id),
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS system_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    value_type TEXT NOT NULL DEFAULT 'string' CHECK (value_type IN ('string', 'number', 'boolean', 'json')),
    description TEXT,
    updated_by TEXT,
    updated_at TEXT NOT NULL,
    FOREIGN KEY (updated_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS books (
    id TEXT PRIMARY KEY,
    owner_user_id TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL DEFAULT 'personal' CHECK (type IN ('personal', 'shared')),
    default_currency TEXT NOT NULL DEFAULT 'CNY',
    icon TEXT,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    FOREIGN KEY (owner_user_id) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS book_members (
    book_id TEXT NOT NULL,
    user_id TEXT NOT NULL,
    role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'editor', 'viewer')),
    status TEXT NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'invited', 'removed')),
    joined_at TEXT NOT NULL,
    PRIMARY KEY (book_id, user_id),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS accounts (
    id TEXT PRIMARY KEY,
    book_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('cash', 'debit_card', 'credit_card', 'ewallet', 'savings', 'investment', 'other')),
    currency TEXT NOT NULL DEFAULT 'CNY',
    opening_balance INTEGER NOT NULL DEFAULT 0,
    cached_balance INTEGER NOT NULL DEFAULT 0,
    icon TEXT,
    color TEXT,
    include_in_assets INTEGER NOT NULL DEFAULT 1 CHECK (include_in_assets IN (0, 1)),
    credit_limit INTEGER,
    statement_day INTEGER CHECK (statement_day IS NULL OR statement_day BETWEEN 1 AND 31),
    repayment_day INTEGER CHECK (repayment_day IS NULL OR repayment_day BETWEEN 1 AND 31),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id)
  )`,
  `CREATE TABLE IF NOT EXISTS categories (
    id TEXT PRIMARY KEY,
    book_id TEXT NOT NULL,
    created_by TEXT,
    parent_id TEXT,
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('income', 'expense')),
    icon TEXT NOT NULL,
    color TEXT,
    is_system INTEGER NOT NULL DEFAULT 0 CHECK (is_system IN (0, 1)),
    sort_order INTEGER NOT NULL DEFAULT 0,
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (parent_id) REFERENCES categories(id)
  )`,
  `CREATE TABLE IF NOT EXISTS tags (
    id TEXT PRIMARY KEY,
    book_id TEXT NOT NULL,
    name TEXT NOT NULL,
    color TEXT,
    created_at TEXT NOT NULL,
    archived_at TEXT,
    UNIQUE (book_id, name),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS transactions (
    id TEXT PRIMARY KEY,
    book_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    account_id TEXT NOT NULL,
    transfer_account_id TEXT,
    category_id TEXT,
    type TEXT NOT NULL CHECK (type IN ('expense', 'income', 'transfer')),
    amount INTEGER NOT NULL CHECK (amount > 0),
    currency TEXT NOT NULL DEFAULT 'CNY',
    base_amount INTEGER NOT NULL CHECK (base_amount > 0),
    base_currency TEXT NOT NULL DEFAULT 'CNY',
    occurred_at TEXT NOT NULL,
    date_key TEXT NOT NULL,
    note TEXT,
    merchant_name TEXT,
    source TEXT NOT NULL DEFAULT 'manual' CHECK (source IN ('manual', 'ai', 'import', 'recurring')),
    status TEXT NOT NULL DEFAULT 'posted' CHECK (status IN ('posted', 'pending', 'void')),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    deleted_at TEXT,
    CHECK (
      (type IN ('expense', 'income') AND transfer_account_id IS NULL AND category_id IS NOT NULL)
      OR
      (type = 'transfer' AND transfer_account_id IS NOT NULL AND category_id IS NULL AND transfer_account_id <> account_id)
    ),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (account_id) REFERENCES accounts(id),
    FOREIGN KEY (transfer_account_id) REFERENCES accounts(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
  )`,
  `CREATE TABLE IF NOT EXISTS transaction_tags (
    transaction_id TEXT NOT NULL,
    tag_id TEXT NOT NULL,
    book_id TEXT NOT NULL,
    PRIMARY KEY (transaction_id, tag_id),
    FOREIGN KEY (transaction_id) REFERENCES transactions(id) ON DELETE CASCADE,
    FOREIGN KEY (tag_id) REFERENCES tags(id) ON DELETE CASCADE,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
  )`,
  `CREATE TABLE IF NOT EXISTS budgets (
    id TEXT PRIMARY KEY,
    book_id TEXT NOT NULL,
    created_by TEXT NOT NULL,
    name TEXT NOT NULL,
    category_id TEXT,
    amount INTEGER NOT NULL CHECK (amount > 0),
    currency TEXT NOT NULL DEFAULT 'CNY',
    period_start TEXT NOT NULL,
    period_end TEXT NOT NULL,
    alert_threshold INTEGER NOT NULL DEFAULT 80 CHECK (alert_threshold BETWEEN 1 AND 100),
    created_at TEXT NOT NULL,
    updated_at TEXT NOT NULL,
    archived_at TEXT,
    CHECK (period_start <= period_end),
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE,
    FOREIGN KEY (created_by) REFERENCES users(id),
    FOREIGN KEY (category_id) REFERENCES categories(id)
  )`,
  `CREATE INDEX IF NOT EXISTS idx_users_system_role ON users(system_role, deleted_at)`,
  `CREATE INDEX IF NOT EXISTS idx_registration_invites_status ON registration_invites(status, expires_at)`,
  `CREATE INDEX IF NOT EXISTS idx_books_owner ON books(owner_user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_book_members_user ON book_members(user_id, status)`,
  `CREATE INDEX IF NOT EXISTS idx_accounts_book ON accounts(book_id, archived_at, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_categories_book_type ON categories(book_id, type, archived_at, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_tags_book ON tags(book_id, archived_at)`,
  `CREATE INDEX IF NOT EXISTS idx_transactions_book_date ON transactions(book_id, date_key DESC, occurred_at DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_transactions_account_date ON transactions(account_id, date_key DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_transactions_category_date ON transactions(category_id, date_key DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_transactions_type_date ON transactions(book_id, type, date_key DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_transactions_not_deleted ON transactions(book_id, deleted_at, date_key DESC)`,
  `CREATE INDEX IF NOT EXISTS idx_transaction_tags_tag ON transaction_tags(tag_id)`,
  `CREATE INDEX IF NOT EXISTS idx_transaction_tags_book ON transaction_tags(book_id, tag_id)`,
  `CREATE INDEX IF NOT EXISTS idx_budgets_book_period ON budgets(book_id, archived_at, period_start, period_end)`,
  `CREATE INDEX IF NOT EXISTS idx_budgets_category_period ON budgets(category_id, period_start, period_end)`
]

export async function ensureSchema(db: D1Database) {
  for (const statement of schemaStatements) {
    await db.prepare(statement).run()
  }
}
